### ISSUE TITLE
Trained speaker model to run inference on

### ISSUE THREAD

**Issue by akhilperincherry** [jialuli-luka/PanoGen#1]
Hello,

Great work and thanks for sharing your work. I was trying to use your speaker model to run inference on VLN data -

  1. Would you be able to release your trained speaker model that was pre-trained with mPLUG?
  2. What is the process to run inference with your speaker model on MP3D data (R2R/RxR)?
  3. Do I need to download VQA dataset or any additional dataset if I just want to run speaker model inference?

Thanks.

**Comment by Pano-Gen** [comment]
Hi,

    1. Now the trained speaker can be found here: https://www.dropbox.com/s/mb0p4zfubejczlm/speaker_checkpoint_04.pth?dl=0.
    2. To run inference on MP3D data, run bash scripts/vln_inference.sh in mPLUG. You need to change the config file and create a ``test file list'' which contains all the paths you want to inference on. 
    3. You don't need to download other datasets if you only want to run speaker model inference. 

Jialu

**Comment by jialuli-luka** [comment]
Hi,
1. Now the trained speaker can be found here: https://www.dropbox.com/s/mb0p4zfubejczlm/speaker_checkpoint_04.pth?dl=0.
2. To run inference on MP3D data, run bash scripts/vln_inference.sh in mPLUG. You need to change the config file and create a ``test file list'' which contains all the paths you want to inference on. 
3. You don't need to download other datasets if you only want to run speaker model inference. 

Jialu

**Comment by akhilperincherry** [comment]
Thank you, that's helpful. I placed the model file inside `mPLUG/speaker` and referenced it to checkpoint parameter in the shellscript file `vln_inference.sh`.

In addition, I referenced `test_file` in `vln_speaker_inference.yaml` with R2R's json file. LMK if these steps are incorrect. Additional questions - 

1. What are the models referenced [here](https://github.com/jialuli-luka/PanoGen/blob/461c2fbb48b0bba8ad8f75cb6847645d79b9022e/mPLUG/models/visual_transformers.py#L43)? Is this the standard CLIP pretrained model? I see you're using a local checkpoint file, so I wanted to confirm if this is different from the standard CLIP ViT-B16.
2. I'm a bit unclear on your data structure for the viewpoints. I see you have `vln_root = views_img`, and inside that or "views_img_sd", it seems like you have a bunch of viewpoint images. Are these panoramas or single view images?
3. How were the above view images obtained, were they viewpoints aggregated (matterport_color_images?) from all the scanfolders of MP3D dataset? I'm trying to replicate the same structure so any guidance would be useful.
4. From the paper, it looks like the speaker was trained using single view images. Is my understanding correct?
5. Would you be able to show how your `lists_train` and `lists_prevalent_inference` look like?
6. Did you install [Apex](https://github.com/NVIDIA/apex) from source? Was there a particular version you would recommend?

**Comment by jialuli-luka** [comment]
First, The test_file should be a list file containing all the training/inference examples, each line in the test_file should look like this:

{"instruction_id": "6250", "path": ["VLzqgDo317F/af3af33b0120469c9a00daa0d0b36799/18.jpg", "VLzqgDo317F/5be145994f974347850a48cecd04cdcd/22.jpg", "VLzqgDo317F/79aedad1206b4eea9c4b639ea2182eb7/0.jpg", "VLzqgDo317F/1c91ed40af2246f2b126dd0f661970df/0.jpg", "VLzqgDo317F/385019f5d018430fa233d483b253076c/12.jpg", "VLzqgDo317F/fd263d778b534f798d0e1ae48886e5f3/12.jpg"]}

1. It should be a standard CLIP ViT-B/16 checkpoint, I download it following the instructions from mPLUG repository. 
2. These are single-view images. views_img is the original images from MP3D, and views_img_sd is the images generated with stable diffusion (w/o outpainting). If you want to reference the original MP3D dataset, you only need the views_img folder. 
3. I'm not sure how to obtain these images if not already given in the dataset. You might be able to discretize these images from the panorama. 
4. Yes the speaker is trained using single-view images. 
5. As shown above. 
6. yes you need to install apex from the source, as pip install apex will install another irrelevant library. I don't remember I specify the version for apex so any version should be fine.

**Comment by akhilperincherry** [comment]
Thank you so much for providing clarity. 

1. Re Test file: So it looks like path is in the format <Scan/viewpointID/viewIndex.jpg> where viewIndex is one of the 36 views. These are the single view images of the trajectory as opposed to the panos right? Did you use the pose traces to get the correct view images from the panos? Is the processing script to get the path single images and arrange them in this order of your train lists available somewhere?

2. Re Apex: I was able to successfully build Apex from source however there seems to be some incompatibility with half tensors and float tensors in the code base. Would you be able to tell me your pytorch version, it's CUDA compile version and the commit ID you used of Apex?

**Comment by jialuli-luka** [comment]
1. Yes it's in the format of  <Scan/viewpointID/viewIndex.jpg>. I get the correct view images based on heading and elevation. You could refer to DUET (https://github.com/cshizhe/VLN-DUET/tree/main), where they provide a scanvp_candview_relangles.json file that contains this information. 
2. I check my environment with pip list env, and it shows that apex==0.1, and torch==2.0.0. For cuda version, nvcc-V gives 10.1, and nvidia-smi gives 11.5.

**Comment by akhilperincherry** [comment]
1. I see, I'll try to render the images using those angular information.
2. Thank you, could you also tell me the commit hashID? You could go to your apex folder, so `cd apex` and then `git log`. You should see commit hashID listed of your clone of the Apex repo. If you can tell me that or paste the screenshot here, I could checkout the same commit and rebuild.

**Comment by jialuli-luka** [comment]
Here's the commit hashID: 
commit 85e9eddece9d4ac72b48c2407f8162f2173e1bf4 (HEAD -> master, origin/master, origin/HEAD)

**Comment by akhilperincherry** [comment]
I'm still getting the issue with half tensor and float tensor when apex is initialized. I tried using multiple different commits of apex and different pytorch+cuda versions. Have you ever come across something like below:

```
  File "vln_mplug.py", line 473, in <module>
    main(args, config)
  File "vln_mplug.py", line 348, in main
    model, optimizer = amp.initialize(model, optimizer, opt_level="O1")
  File "/nfs/hpc/sw/perincha/conda-envs/panogen-env/lib/python3.8/site-packages/apex/amp/frontend.py", line 358, in initialize
    return _initialize(models, optimizers, _amp_state.opt_properties, num_losses, cast_model_outputs)
  File "/nfs/hpc/sw/perincha/conda-envs/panogen-env/lib/python3.8/site-packages/apex/amp/_initialize.py", line 171, in _initialize
    check_params_fp32(models)
  File "/nfs/hpc/sw/perincha/conda-envs/panogen-env/lib/python3.8/site-packages/apex/amp/_initialize.py", line 84, in check_params_fp32
    warn_or_err("Found param {} with type {}, expected torch.cuda.FloatTensor.\n"
  File "/nfs/hpc/sw/perincha/conda-envs/panogen-env/lib/python3.8/site-packages/apex/amp/_amp_state.py", line 33, in warn_or_err
    raise RuntimeError(msg)
RuntimeError: Found param visual_encoder.text_projection with type torch.cuda.HalfTensor, expected torch.cuda.FloatTensor.
When using amp.initialize, you do not need to call .half() on your model
before passing it, no matter what optimization level you choose.
Traceback (most recent call last):
  File "/nfs/hpc/sw/perincha/conda-envs/panogen-env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nfs/hpc/sw/perincha/conda-envs/panogen-env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/nfs/hpc/sw/perincha/conda-envs/panogen-env/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/nfs/hpc/sw/perincha/conda-envs/panogen-env/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/nfs/hpc/sw/perincha/conda-envs/panogen-env/bin/python', '-u', 'vln_mplug.py', '--config', './configs/vln_speaker_inference.yaml', '--output_dir', 'speaker/', '--checkpoint', 'speaker/speaker_checkpoint_04.pth', '--do_two_optim', '--min_length', '15', '--beam_size', '10', '--max_length', '80', '--max_input_length', '25', '--evaluate', '--do_amp']' returned non-zero exit status 1.
```

**Comment by jialuli-luka** [comment]
I haven't met this issue before.

According to the error message, you might want to check the dtype of parameters in visual_encoder.text_projection in the clip model, and convert it to float() type.

**Comment by akhilperincherry** [comment]
Thank you, I'll look into it. I recently was able to render single view images using the discretized simulator to run inference on your speaker model. I had a few questions on rendering images to replicate the setting you used:
1. I see that the model expects images of shape 448x448. To render images from the simulator, did you use these dimensions by passing it to `sim.setCameraResolution()` or did you first render 640x480 images using the simulator and then rescaled them to 448x448?
2. What FoV did you use in `sim.setCameraVFOV()`?

**Comment by jialuli-luka** [comment]
I use 640*480 images as input and resize them to 448*448. 
We set sim.setCameraVFOV(x), where x = math.radians(60).

**Comment by akhilperincherry** [comment]
So I was just creating a sample test set in the below format and had a couple of questions -
```
{"instruction_id": "6250", "path": ["VLzqgDo317F/af3af33b0120469c9a00daa0d0b36799/18.jpg", "VLzqgDo317F/5be145994f974347850a48cecd04cdcd/22.jpg", "VLzqgDo317F/79aedad1206b4eea9c4b639ea2182eb7/0.jpg", "VLzqgDo317F/1c91ed40af2246f2b126dd0f661970df/0.jpg", "VLzqgDo317F/385019f5d018430fa233d483b253076c/12.jpg", "VLzqgDo317F/fd263d778b534f798d0e1ae48886e5f3/12.jpg"]}
```

1. How do you get the `instruction_id`? I see them being present only in RxR but from the paper it looks like you use R2R mainly.
2. How did you compute the relative elevation to select the correct single view image from a pano in a path sequence?
3. Did you also use the final stop image from the path? If so, how did you select the stop image from the final panorama?
4. Would you be able to upload `/nas-hdd/jialu/pretrained_model/ViT-B-16.tar` CLIP model? There seems to be some discrepancy between the latest CLIP models and the ones used in this code. Discrepancy explained below:
    - I tried using the download link for Vit-B16 from [here](https://github.com/openai/CLIP/blob/main/clip/clip.py#L30-L40). However, that model has inconsistencies with [this line](https://github.com/jialuli-luka/PanoGen/blob/main/mPLUG/models/clip/clip.py#L83) since there is no `input_resolution`.
    - To get around this, rather than using the clip model from this codebase, I directly did `import clip` to use the latest clip model which has `visual.input_resolution` and that got through this line. However, eventually while doing speaker model inference that fails [here](https://github.com/jialuli-luka/PanoGen/blob/main/mPLUG/models/model_caption_mplug_vatex.py#L45) because `skip_last_layer` has been removed from the latest CLIP codebase now, as can be seen from their official [repo](https://github.com/openai/CLIP/blob/a9b1bf5920416aaeaec965c25dd9e8f98c864f16/clip/model.py) which is inconsistent with the CLIP code from mPLUG.
    - If I run the latest CLIP model from online with the CLIP code here, I get inconsistent keys like `_IncompatibleKeys(missing_keys=['visual_encoder.input_resolution', 'visual_encoder.context_length', 'visual_encoder.vocab_size'], unexpected_keys=[])`.
    - If I can get the exact CLIP model you used, I could use the same model definition from this codebase and replicate the results. :)

**Comment by jialuli-luka** [comment]
Hi,
1. The instruction_id is mainly used for identifying the path, actually you could use any number/string as you want as long as you can get the correspondence. In my case, I use the concatenation of path id and the instruction num (e.g., the second instruction out of the three annotated instructions on R2R) as the instruction id. 
2. I get the heading and elevation from DUET's scanvp_candview_relangles.json. Or you could calculate it based on the Matterport3D's state. 
3. I select it based on the agents' heading and elevation at each step (including the final panorama). The heading and elevation of the first panorama are given in the R2R dataset. 
4. I download the CLIP from mPLUG repository: https://github.com/X-PLUG/mPLUG. You could find the download link there: https://alice-open.oss-cn-zhangjiakou.aliyuncs.com/mPLUG/ViT-B-16.tar

**Comment by akhilperincherry** [comment]
Thank you so much, that CLIP model seems to fix the inference issue.

1. Re 2: Does the view index in scanvp_candview_relangles follow the same convention from [here](https://github.com/peteanderson80/Matterport3DSimulator/blob/589d091b111333f9e9f9d6cfd021b2eb68435925/scripts/precompute_img_features.py#L98)?
2. Re 2: Is it possible to associate the entries in scanvp_candview_relangles to the corresponding instruction? I see scan_vp, relative distance, heading, elevation and pano ID being listed but not instruction ID or path ID.
3. Re 2 again: I have been rendering from the simulator directly based on R2R's annotations but I'm not fully sure if my relative elevations are correct since they barely change in most of the scenes. Do you have have relative elevations that you computed between two panos? Or did you just use scanvp_candview_relangles?
4. Re 3: To ensure I understood correctly, if the path length is 4, then you would have relative heading and elevation for the first 3 panos but not the 4th right? For the 4th, the agent would be within 3m from the destination, so I would expect the center of the pano to be roughly the correct single image. Is this the image you use for the final pano? In otherwords, if path length is 4, do you feed 4 images or 3 images to train the speaker model?
5. Re 3: The heading of the first pano is given in the R2R data but I don't see the elevation. I'm guessing that might be because they're always zero for the first pano?

**Comment by jialuli-luka** [comment]
Hi,
1. yes.
2. Yes. The relative heading and elevation are independent of instruction/path. 
3. I use scanvp_candview_relangles.
4. We have relative heading and elevation for the last three panos. The elevation and heading for the first angle is in the R2R dataset.
5. Yes we assume the elevation to be 0.

**Comment by akhilperincherry** [comment]
Thank you so much. To confirm if I understood correctly, scanvp_candview_relangles is like a look up table to obtain relative heading, elevation and distance between any two panos in R2R?

**Comment by jialuli-luka** [comment]
Yes scanvp_candview_relangles is like a look up table to obtain relative heading, elevation between any two panos in R2R. I'm not sure whether the distance is included in the file.

**Comment by akhilperincherry** [comment]
Gotcha, thank you so much for all the help, I'll close this issue.
