### ISSUE TITLE
How to generate panoramic caption

### ISSUE THREAD

**Issue by lizixiaoboluo** [jialuli-luka/PanoGen#2]
Why is my Matterport3D data different from yours？ I noticed that views_img has a different directory structure, e.g., 'views_img/r1Q1Z4BcV1o/a72aa7b4304f4c318af76653d9950c80/5.jpg', which is different from the original directory structure in matterport3d.Such as  the original directory structure in matterport3d is '0b22fa63d0f54a529c525afbf2e8bb25_skybox0_sami.jpg'. Why is 
 my  Matterport3D data diffenent?   Thank you for your patience.

**Comment by jialuli-luka** [comment]
You could get the discretized RGB images from the matterport3D simulator.

**Comment by lizixiaoboluo** [comment]
How to save the discretized RGB images from the matterport3D simulator to my computer？Thank you for your patience again！

**Comment by jialuli-luka** [comment]
You could refer to the image feature extraction code here for how to use the simulator and get the RGB information: https://github.com/cshizhe/VLN-HAMT/blob/main/preprocess/precompute_img_features_vit.py

**Comment by lizixiaoboluo** [comment]
Think you very much!
