### ISSUE TITLE
How could I get the eval_metrics in the test split?

### ISSUE THREAD

**Issue by tpxbps** [jialuli-luka/PanoGen#4]
hi! 
I found these code in VLN-DUET/map_nav_src/r2r/main_nav.py
```
            if 'test' not in env_name:
                score_summary, _ = env.eval_metrics(preds)
                loss_str = "Env name: %s" % env_name
                for metric, val in score_summary.items():
                    loss_str += ', %s: %.2f' % (metric, val)
                write_to_record_file(loss_str+'\n', record_file)
```
but how can I get the eval_metrics when env_name='test'
thanks!!!

**Comment by jialuli-luka** [comment]
Hi,
    You need to submit the result file to the test leaderboard (e.g., https://eval.ai/web/challenges/challenge-page/97/leaderboard/270) to get the test performance. 
Best,
Jialu

**Comment by tpxbps** [comment]
I see, thank you so much!
